### ISSUE TITLE
NAOProgram: Error during transfer if 'roberta' on robot is not a folder

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#106]
**Describe the bug**
 - The NAO HAL is saved in the /home/nao/roberta folder on the robot.
 - If the roberta folder does not exist or a file is named roberta, scp does not create the folder but overwrites the file. 
 - Then, no program is executed as there is no valid HAL available.
 - This seems to only affect Linux.

**To Reproduce**
1. Connect NAO via NAOProgram
2. Transfer program

**Expected behavior**
 - The transferred program is executed.

**Device information**
 - OS: Linux Ubuntu 18.04

**TODO:**
- [x] Fix
- [x] Test on Windows
  - [x] NAO 5
  - [x] NAO 6
- [x] Test on Linux
  - [x] NAO 5
  - [x] NAO 6
- [x] Test on Mac
  - [x] NAO 5
  - [x] NAO 6
- [x] Release bugfix
