### ISSUE TITLE
Refactor NIBO {BOB3, ROB3RTA} Visitor/Worker

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1258]
Refactor NIBO robots (BOB3, ROB3RTA) to adhere to the structure laid out for other Arduino robots.
Related issue: #1163 

## TASKs
- [ ] Check current implementation
- [ ] Refactor relevant `Bob3UsedHardwareCollector*`, `Bob3UsedMethodCollector*` visitor/worker into `NIBOValidatorAndCollector*` visitor/worker.
- [ ] Remove old (separately used) bob3 visitors/workers.

## TESTs
- [ ] Check changes by running local server.
- [ ] Check changes by running integration tests.
