### ISSUE TITLE
Refactor mBot Visitor/Worker

### ISSUE THREAD

**Issue by munka21** [OpenRoberta/openroberta-lab#1259]
Refactor mBot robot to adhere to the structure laid out for other Arduino robots.
Related issue: #1163 

## TASKs
- [x] Check current implementation
- [x] Refactor relevant `mBotUsedHardwareCollector*`, `mBotUsedMethodCollector*` visitor/worker into `mBotValidatorAndCollector*` visitor/worker.
- [x] Remove old (separately used) mBot visitors/workers.

## TESTs
- [ ] Check changes by running local server.
- [ ] Check changes by running integration tests.
