### ISSUE TITLE
Refactor Edison: Visitor-Worker-Structure

### ISSUE THREAD

**Issue by roffinator3000** [OpenRoberta/openroberta-lab#1262]
Refactor Edison.

## TASKs
- [ ] Check current implementation
- [ ] Refactor relevant `EdisonUsedHardwareCollector*`, `EdisonUsedMethodCollector*` visitor/worker into `EdisonValidatorAndCollector*` visitor/worker.
- [ ] Update `edison.properties`.
- [ ] Remove old visitors/workers.

## TESTs
- [ ] Check changes by running local server.
- [ ] Check changes by running integration tests.
