### ISSUE TITLE
Refactor Bot'n Roll Visitor/Worker

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1263]
Refactor Bot'n Roll to adhere to the structure laid out for other Arduino robots.
Related issue: https://github.com/OpenRoberta/openroberta-lab/pull/1163

## TASKs

- [x] Check current implementation.
- [x] Refactor relevant `BotnrollUsedHardwareCollector*`, `BotnrollUsedMethodCollector*` visitor/worker into `BotnrollValidatorAndCollector*` visitor/worker.
- [x] Remove old (separately used) bot'n roll visitors/workers.

## TESTs

- [x] Check changes by running local server.
- [x] Check changes by running integration tests.
