### ISSUE TITLE
Refactor WeDo: Visitor-Worker-Structure

### ISSUE THREAD

**Issue by roffinator3000** [OpenRoberta/openroberta-lab#1268]
Refactor WeDo.

## TASKs
- [ ] Check current implementation
- [ ] Refactor relevant `WeDoUsedHardwareCollector*`, `WeDoUsedMethodCollector*` visitor/worker into `WeDoValidatorAndCollector*` visitor/worker.
- [ ] Update `wedo.properties`.
- [ ] Remove old visitors/workers.

## TESTs
- [ ] Check changes by running local server.
- [ ] Check changes by running integration tests.
