### ISSUE TITLE
Refactor NXT Visitor/Worker

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1271]
Refactor NXT to adhere to the structure laid out for other robots.

## TASKs

- [x] Check current implementation.
- [x] Refactor relevant `NxtUsedHardwareCollector*`, `NxtUsedMethodCollector*` visitor/worker into `NxtValidatorAndCollector*` visitor/worker.
- [x] Refactor relevant visitor/worker into `NxtSimValidatorAndCollector*` visitor/worker.
- [x] Remove old (separately used) nxt visitors/workers.

## TESTs

- [x] Check changes by running local server.
- [x] Check changes by running integration tests.
