### ISSUE TITLE
Refactor RaspberryPi Visitor/Worker

### ISSUE THREAD

**Issue by munka21** [OpenRoberta/openroberta-lab#1294]
Refactor RaspberryPi to adhere to the structure laid out for other robots.

## TASKs

- [ ] Check current implementation.
- [ ] Refactor relevant `RaspberryPiUsedHardwareCollector*`, `RaspberryPiUsedMethodCollector*` visitor/worker into `RaspberryPiValidatorAndCollector*` visitor/worker.
- [ ] Remove old (separately used) nxt visitors/workers.

## TESTs

- [ ] Check changes by running local server.
- [ ] Check changes by running integration tests.

**Comment by rbudde** [comment]
refers to an outdated plugin.
