### ISSUE TITLE
Integration of the Edison V2 robot into the OpenRoberta Lab.

### ISSUE THREAD

**Issue by uzkns** [OpenRoberta/openroberta-lab#173]
#### To-Do:
- [x] Create a new branch in Git
- [x] Add Edison robot to Maven #174 
- [x] Implement code generation and compiler workflow
    Blockly blocks need to be converted to EdPy (Python 2.7) code, see  [here](https://meetedison.com/content/EdPy-app-documentation-guide.pdf) and [here](https://github.com/Bdanilko/EdPy/blob/master/doc/edpy-language.pdf)
    Then, the EdPy code needs to be converted to a WAV file, see [here](https://github.com/Bdanilko/EdPy)
- [x] Add Blockly blocks and edit toolbox
    Create brick-specific blocks and a toolbox
- [x] Add images for Edison robot
    - Thumbnail, f.e. for the "Choose your system" dialog
    - Background for the code editor
    - Since the brick cannot be modified (all sensors/motors are fixed) it needs an explanation image in the "robot configuration" tab (like the [NAO](https://lab.open-roberta.org/css/img/naoBackgroundConf.svg) or the [Calliope](https://lab.open-roberta.org/css/img/calliopeBackgroundConf.svg))
- [x] Code cleanup and inspection
    Cleanup the code and remove legacy files/classes

#### Brick overview:
The Edison V2 robot has a 2-wheel drive system which can drive forwards/backwards for `Ed.DistanceUnits`. Each motor can be individually addressed and turned also.

**NOTE**: *Edison V1 has no rotary encoder and can only drive/turn for a certain time (`Ed.DistanceUnits = Ed.TIME`). Edison V2 can also drive for a certain length or turn a certain degree (`Ed.CM`)*

Edison has 2 IR LEDs on the front which can send and receive data from other robots or remote controls. These LEDs also work as an obstacle detection system.

On the front, there are also two light sensors and two red LEDs.

On the bottom, Edison has a line tracker consisting of a red LED and a light sensor (this also doubles as the EdComm cable port)

On the top are the controls (start, stop, record) as well as a Piezo speaker and a sound sensor.

More information on the Edison robot can be found [here](https://meetedison.com/). The technical overview of the brick can be found [here](https://meetedison.com/technical/) and [here](https://github.com/Bdanilko/EdPy/blob/master/doc/ed-tokens.pdf).

#### Data transfer:
Edison uses a 3,5mm phone connector (["EdComm" cable](https://meetedison.com/product/edcomm-10-pack/)) for data transfer via audio files. The generated Python code is compiled into a WAV file and then played through the PCs headphone jack after the "record" button the Edison is pressed. Read more about this process [here](https://github.com/Bdanilko/EdPy).
