### ISSUE TITLE
collection of errors related to simulation and WeDo

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#215]
- _the null value is not handled at all. It is unclear, how it should behave. See #21_  <- same for master, not relevant here
- [x] the switch led on (to red e.g.) crashes the simulation
- [x] Roberta Mobile App freezes, if a loop is used without "wait ms" block in it. See #192
- [x] WeDo has only one timer, but can reset five. See #212
- [x] Functions with deactivated blocks may not be executed correctly in the simulation. See #198
- [x] WeDo-Program with "play frequency Hz" block is not be executed. See #191
- _Simulation does not open if ternary block, with empty branch, is in task. See #203_ <- same for master, not relevant here
- [x] Testing multiple robots in simulation
- Unify the simulation constants and interpreter constants, not relevant for the release
- [x] Set Motor Port B speed % (EV3)
- [x] Invalid statement op: math change
- [x] Invalid statement op MathPropFunct, TextAppend
- [x] Using for-each leads to bug in opening the sim 
- [x] Count loop terminates if _i_ is used in _if_ without _else_ stmt
- [x] Calliope "turn LED internal on" turns right wheel to white
- [x] EV3 math power does nothing (invalid supOp POWER)
- [x] Calliope set brightness does nothing
- [x] Calliope "debug" does not print to console
- [x] EV3 math all floats considered odd?
- _Calliope "temp" sensor does not work_ <- same for master, not relevant here
- [x] nxt colour == colour doesn't work
- [x] nxt set colour sensor on doesn't work
- [x] for each in list doesn't work
-  _muliple sim: first 2 robots, then 1 robot, still 2 available_ <- same for master, not relevant here
-  EV3 lists: get and remove from empty lists <- same for master, not relevant here
-  EV3 lists: pop failed with empty  <- same for master, not relevant here
- [x] EV3 lists: remove does not work (invalid op on LIst function Name)
- [x] EV3 lists:List set does not modify first
- EV3 lists: not null -> false, null -> false  <- same for master, not relevant here
- [x] Calliope "color with" breaks sim -> invalid stmt op rgbColor
- _Change by TEXT Tooltip wrong_ <- same for master, not relevant here
- _random int between 0, 0.9 returns 1_ <- same for master, not relevant here
- [x] NXT sound sensor not working
- [x] WeDo show text not working (Android & IOS)
- [x] EV3: interpreter.util.js:14 Uncaught invalid stmt op: CurveAction
Some old issues:
- [x] Cant't open simulation when using text append block (old 1116)
- [x] EV3Sim Lists wrong behaviour (old 1008)

**Comment by bjost2s** [comment]
at current state we have the following problem with timing (example calliope)
![image](https://user-images.githubusercontent.com/1613069/63640803-27bb4a80-c6a5-11e9-8c2e-2bc602cf105b.png)
generates with the old simulation (master) the following output:
![image](https://user-images.githubusercontent.com/1613069/63640826-5d603380-c6a5-11e9-80fb-fcbf124c1749.png)
and here the output from the new simulation (develop)
![image](https://user-images.githubusercontent.com/1613069/63640848-99939400-c6a5-11e9-8612-9f47fcc8c5ac.png)
Both are far away from the real calliope output:
2045
19
2046
19
2046
19
2046
19
2046
19
2046
19
2046
19
2046
19
2046
19
2046
19
The new behavior will break almost all user programs which depends on time.
