### ISSUE TITLE
As a kid I would like to create programs for the EV3 running the stock firmware

### ISSUE THREAD

**Issue by simonedegiacomi** [OpenRoberta/openroberta-lab#27]
Issue for the GSoC project "EV3 as a storage device".

- [x] c4ev3 compiler workflow #28 
- [x] c4ev3 code generation #29 
- [x] add support to c4ev3 for missing sensors/features #30
