### ISSUE TITLE
EV3: Adjust sensor configurations

### ISSUE THREAD

**Issue by philipp-s4** [OpenRoberta/openroberta-lab#958]
As a user I would like to adjust the sensor configuration of my EV3 robot so I can implement similar configurations in the simulation as I can specify them on the actual EV3 robot.

As a user I would like to specify the:  
- [ ] sensor position: adjusts the position of the sensor on the robot  
	- [ ] color sensor position ([User Story](https://github.com/OpenRoberta/openroberta-lab/issues/943))
	- [ ] touch sensor position ([User Story](https://github.com/OpenRoberta/openroberta-lab/issues/944))
	- [ ] ultrasensor position ([User Story](https://github.com/OpenRoberta/openroberta-lab/issues/946))
	- [ ] infrared position ([User Story](https://github.com/OpenRoberta/openroberta-lab/issues/947))
- [ ] sensor alignment: adjusts the orientation of the sensor on the robot  
	- [ ] color sensor alignment ([User Story](https://github.com/OpenRoberta/openroberta-lab/issues/945))
	- [ ] ultrasonic alignment ([User Story](https://github.com/OpenRoberta/openroberta-lab/issues/950))
- [ ] track width of the robot ([User Story](https://github.com/OpenRoberta/openroberta-lab/issues/948))
